/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class learn_jni_math_calc_Calculator */

#ifndef _Included_learn_jni_math_calc_Calculator
#define _Included_learn_jni_math_calc_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     learn_jni_math_calc_Calculator
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_learn_jni_math_calc_Calculator_square
  (JNIEnv *, jobject, jint);

/*
 * Class:     learn_jni_math_calc_Calculator
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_learn_jni_math_calc_Calculator_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     learn_jni_math_calc_Calculator
 * Method:    subtract
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_learn_jni_math_calc_Calculator_subtract
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     learn_jni_math_calc_Calculator
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_learn_jni_math_calc_Calculator_multiply
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
